#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Use nvm to select the correct Node.js version
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use 22 &> /dev/null

npm run lint-staged
